# Generated by Django 4.0.1 on 2022-01-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='desc',
            field=models.CharField(default='vazia', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.CharField(default='vazia', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='st_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
