# Generated by Django 4.0.1 on 2022-01-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.IntegerField(),
        ),
    ]
