# Generated by Django 4.0.1 on 2022-01-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_categories_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
