# Generated by Django 4.0.1 on 2022-02-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_content_comment_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='bid',
            name='value',
            field=models.IntegerField(default=-1),
        ),
    ]
