# Generated by Django 4.0.1 on 2022-02-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_listing_id_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
