# Generated by Django 4.0.1 on 2022-02-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_bid_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.IntegerField(default=-1),
        ),
    ]
